### ISSUE TITLE
タイトルに「-」がある場合、タイトルが消え、「-」以降のテキストもすべて消えます

### ISSUE THREAD

**Issue by Sakrecoer** [pooza/tomato-shrieker#1093]
## 概要

タイトルに「-」がある場合、タイトルが消え、「-」以降のテキストもすべて消えます

## 環境

tomato-shrieker v3.5.5
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [armv7l-linux-eabihf]

**Comment by Sakrecoer** [comment]
タイトルの例: https://v.basspistol.org/w/mFpcSomnekk5h8cNM4MMLD

misskey に見られるメモ: https://s.basspistol.org/notes/9ng7lrs0xv

**Comment by Sakrecoer** [comment]
テンプレート
```
[<%= @params[:feed].prefix %>] 
<%= @params[:entry].title %>

🎬 <%= @params[:entry].uri %>

<%= @params[:entry].summary %>

<% if @params[:tag] -%>
🈁 <%= @params[:entry].tags.join(' ') %>
<% end -%>

```

**Comment by Sakrecoer** [comment]
申し訳ありませんが、問題はトマトシュリーカーではなく、RSS フィードです

**Comment by Sakrecoer** [comment]
タイトルがCDATAにある場合に起こるようです
`<![CDATA[GravoBoy - GIESELHER]]>`

**Comment by pooza** [comment]
@Sakrecoer 
ご報告ありがとうございました。しばらく気付いておらずすみません。
次バージョンで対応できる様、調査します。

**Comment by Sakrecoer** [comment]
@pooza ご返答ありがとうございました。 楽しみにしている！ それまで、幸せな週末をお祈りします！

**Comment by pooza** [comment]
@Sakrecoer 
テンプレートを拝見したところ、ソースはRSSフィードですよね。そちらも拝見できますか？

**Comment by Sakrecoer** [comment]
@pooza 
確かにソースは RSS です。

私の日本語を許してください。 文章を書いたり読んだりするために翻訳ツールを使用しています。 したがって、私があなたの質問を誤解している可能性があります。

**Comment by pooza** [comment]
@Sakrecoer 
If an RSS feed is the cause, what is the source or URL of the feed that causes the same error?

> 私の日本語を許してください。 文章を書いたり読んだりするために翻訳ツールを使用しています。 したがって、私があなたの質問を誤解している可能性があります。

Rather, please forgive me that I am not English either. I will also be conversing with you through machine translation.

**Comment by Sakrecoer** [comment]
@pooza 
ありがとう！ (^^,)
もしかしたらこうやって一緒に学べるかも！
エラーの原因となるフィードは次のとおりです。 
https://v.basspistol.org/feeds/videos.xml?sort=-publishedAt&isLocal=true

**Comment by pooza** [comment]
@Sakrecoer 
Thank you very much.
I think I can reproduce the phenomenon with the information you provided.

By the way, I use Feedjira for RSS and Atom analysis.
https://github.com/feedjira/feedjira

I think the CDATA problem is also a behavior on the Feedjira side.
As a countermeasure, we are considering processing the CDATA before passing it to Feedjira.

**Comment by pooza** [comment]
@Sakrecoer おまたせしました。対応済みです！

**Comment by Sakrecoer** [comment]
@pooza 
すばらしい！ どうもありがとうございます！
