### ISSUE TITLE
Discordにリンク付きで投稿した際に、たまに埋め込みが空になることがある

### ISSUE THREAD

**Issue by karasugawasu** [pooza/tomato-shrieker#886]
## 概要
Discordにリンク付きで投稿した際に、たまに埋め込みが空になることがある

## 現象

Discordにリンクを貼り付けた際に、通常であればサイトのプレビューが埋め込まれますが、
まれに(1/2くらい)空の状態のものが作成されます。
![image](https://user-images.githubusercontent.com/29486402/185932076-d0febd7b-3572-41b4-902b-97343506664f.png)

なお、手動でリンクを張った際や、curlを使った場合は問題なく(この場合)Twitterの埋め込みが表示されます。

一度表示されなかったリンクは、何回やってもダメでした。

正直、Discordの不具合かと思ってますが・・、
他のDiscordサーバのTwitterBOTなどでそのような不具合が見られないことや、
curlや手動では問題ないことから可能性がなくはないかなと思ってこちらに記載します。

## 期待される動作

正しく埋め込みが表示される

## 再現手順

1. 出力をDiscord向けにtomato-shriekerを設定する
2. Twitter等のリンクが共有されるものをソースにする
3. 投稿されると1/2くらいで埋め込みが空になる

## 環境

tomato-shrieker : 3.4.12
CentOS 7.9

**Comment by pooza** [comment]
解決されているようですが、後々の為に調査したいです。
現象の共有の為に、いくつか確認させてください。（発生する現象の認識合わせをしないと、無関係な修正をすることになりかねないので）

> 2. Twitter等のリンクが共有されるものをソースにする
（例えば）TweetTimelineSource からWebhookShrieker利用するという意味ですか？

> 3. 投稿されると1/2くらいで埋め込みが空になる
TweetTimelineSourceからWebhookShrieker宛に投稿すると、本文がURLを含みます。
Discord宛に投稿したことがないのですが、通常は本文中に埋め込み（iframe？）が配置されるのですか？

埋め込みがiframeであるとして、以下のどちらかの現象が起きるのですか？
- iframe要素が配置されない
- 壊れた（リンク先のない）iframeが配置される

**Comment by pooza** [comment]
Discordだからiframeもなにもないですね。失礼致しました。

**Comment by karasugawasu** [comment]
> TweetTimelineSource からWebhookShrieker利用

はい、こちらを使用しています。

TwitterにかぎらずURLをDiscordで投稿すると、Discordのembed機能を利用して自動的にTwitterの投稿内容を再現してくれるみたいです。
※こんな感じで
![image](https://user-images.githubusercontent.com/29486402/186358795-19bb0ed2-5277-4445-83a8-28e1a045d5a8.png)

https://discord.com/developers/docs/resources/channel#embed-object

おそらくですが、Discord側でTwitterの情報を取ってきて生成していると思うのですが、何らかが原因で壊れたものが作成されている感じです。
![image](https://user-images.githubusercontent.com/29486402/186359204-daa09c62-98b4-4937-8c1b-1cd5c90cbb66.png)

現状ものによってできたりできなかったりで、規則性はちょっと不明です。
ただ、確認できているのが手動で投稿、curlで投稿などでは特に問題ないことと、
他のDiscordサーバとかを見ていてこのような現象が起きているところが見当たらないのが謎なところです。

ちなみに今はかわりにn8n使っているのですが、そちらだとこの現象は発生していない感じです。

以下試していて、それらでは特に問題は発生しませんでした。
_条件tomato-shriekerでダメだったURLを使用_

- curlで投稿
- curlでslack互換を使って投稿
- 手動で投稿
- 別のツールで投稿

**Comment by pooza** [comment]
規則性があるかも知れないので、 twitter.com で問題がおきたURLのサンプルをいくつか頂いていいですか？

**Comment by karasugawasu** [comment]
遅くなりましたが共有です。

ダメだったURL
```
https://twitter.com/ToF_JP/status/1561911103420071936
https://twitter.com/ToF_JP/status/1561896005326471168
https://twitter.com/ToF_JP/status/1561865811643379712
https://twitter.com/ToF_JP/status/1561699720044523521
https://twitter.com/ToF_JP/status/1561660110690467841
https://twitter.com/ToF_JP/status/1561556025899388928
https://twitter.com/DJMAX_global/status/1563021350285242371
https://twitter.com/DJMAX_global/status/1563021195959685121
https://djmax.store/
```

おまけで大丈夫だったやつです。
```
https://twitter.com/ToF_JP/status/1561563379550273539
https://twitter.com/ToF_JP/status/1561548719916400642
https://twitter.com/ToF_JP/status/1560537060611526656
https://twitter.com/ToF_JP/status/1560461555438800898
```
